#start my route to the actions!
name: My-GitHub-Actions
env:
    MY_APP_NAME: "my-ci-app"
    PACKAGE_NAME: "my-package is ${{ github.sha }}"
on:
    push:
        branches:
            - main
jobs:
    my-second-action:
        runs-on: ubuntu-latest
        steps:
            - name: Run my first action
              run: echo "Hello, GitHub Actions!"

            - name: Greatings
              run: |
                echo "Hello, ${{ github.actor }}!"
                echo "This is my first action!" 
                echo "This is the next step in my first action!"
                echo "My app name is ${{ env.MY_APP_NAME }}"
    my-first-action:
        runs-on: ubuntu-latest
        needs: my-second-action
        steps:
            - name: Run my second action
              run: echo "This is my second action!"
            - name: Package name
              run: |
                echo "My package name is ${{ env.PACKAGE_NAME }}"
                echo "This is the next step in my second action!"